# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subcategory',
            field=models.CharField(default='', max_length=200),
        ),
    ]
