# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_article_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rebelion_id',
            field=models.IntegerField(default=0),
        ),
    ]
