# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20160810_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(default='', max_length=400),
        ),
    ]
