# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_article_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_name',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
