# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20160811_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='license',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='article',
            name='translated_by',
            field=models.CharField(default='', max_length=400),
        ),
    ]
