# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20160811_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_country',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='is_latin_america',
            field=models.BooleanField(default=0),
        ),
    ]
