# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20160811_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_country',
            new_name='is_region',
        ),
    ]
