# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20160811_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_timestamp',
            field=models.IntegerField(db_index=True, default=0, verbose_name='day'),
        ),
    ]
