# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20160813_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='raw',
            field=models.TextField(default=''),
        ),
    ]
