# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20160819_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='raw',
            new_name='raw_body',
        ),
    ]
