# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_article_body_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body_md',
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
