# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20160820_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body_html',
            new_name='body_md',
        ),
    ]
